$ANSIBLE_VAULT;1.1;AES256
62613733313366393561363265343266633134623463306365326136616666643032336166343865
3439346233316432326461633732396432316430353966310a623232363839366631343234303838
33383530613033613736326337613738656232393032653234313330376239353030656665343262
3932346637623438620a616131636233623131363932643237346439633264326161376532326361
64336131373564646231373162373934346462616636643432393737653738383036396539343830
32346465396563366333613934366237333563663231663561343062353030353461666262356234
62383738323561663661333935366366363165616538626532393663643538396237323138386332
65613665626361306461343838306566646166643262386131643232643238613734336666626535
37393831396238343038326562653434363864363332336466323761303633396433306561373036
32393362303438636533636166643464346562323761363731366235313365636165663061306439
393538386661386230303661383337653462
