$ANSIBLE_VAULT;1.1;AES256
37626636393533613962323566323564613462346332643039333964373437303463333834633734
6634303765346233653763376662396333623933303030340a386365343761386333383831633435
38356332343163313261353832306161633964383536643133333031356232326366656564336337
3431366631363464350a346664373565373735393335353738316439373835343831626130316265
61343035353637633263383030623239353765626239303033343138313936313264643138653835
38656362623637396431333765386333366335613035333334393637386434363832373161383131
31306532396463363163376663663530376637326137613264303664393336663036353532333939
35323064643263626534343761323566323438633662633064623832366535353264373766376338
35336537316232333466613130316436383836326633626264663337306232393965326230656235
63623936363239356665366165633134306263666537366138656165393837306435386230616663
36323866353561666361346263666664623265383763376132323361356438636666636165313465
33663766383836306231333961363933353839343936373432373962366161343334353434373839
66616466386362613161373632623832313637613236373536313839646635326466306265323230
64383265376166303364633437616239396338333462623562333563636439336634323133616339
34363862653662623234613165326232326130316161646437353138613362396363376566613861
33303739376434656561326361613839623963333733366562643866303536663835323832663737
38636531326163616665383861643035633737663034363033666438326366383635636230656665
30303062663139616639343631646430386465653666313635646466346336343966343737626231
39313635616538633333306435623165383831643636353638613230333935373238303066383937
35326633373834643733626337363138376638356632643562613331303330623337623332653561
65366430326234316637396261376463346638616632636361626534656632346330623764633636
38633731383563323336363832636234343236363132333537323265376163326261613531383365
35396263396362346562303436306538626332643239656437343634343438656263336335306262
63393935626333323236
